---
title: "STAT 380 Homework Exercises"
subtitle: "MDSR Chapter 09"
author: "Kimberly Mincin"
date: "Due: 24/02/2019"
output: html_notebook
---

# Front matter

```{r}
# always clean up R environment
rm(list = ls())

# load all packages here
library(mdsr)
library(readxl)
library(ape)
library(Lahman)
library(mclust)
```


# Exercises

### Exercise 9.2

```{r}
filename <- list.files("data/fueleconomy", pattern = "public\\.xlsx")[1]

cars <- read_excel(paste0("data/fueleconomy/", filename)) %>%
  data.frame()

cars <-
  cars %>%
  rename(make = Mfr.Name, model = Carline, displacement = Eng.Displ, cylinders = X..Cyl, 
         city_mpg = City.FE..Guide....Conventional.Fuel, hwy_mpg = Hwy.FE..Guide....Conventional.Fuel, 
         gears = X..Gears) %>%
  select(make, model, displacement, cylinders, gears, city_mpg, hwy_mpg) %>%
  distinct(model, .keep_all = TRUE) %>%
  filter(make == "Ferrari")


rownames(cars) <- cars$model

glimpse(cars)

car_diffs <- dist(cars)

str(car_diffs)

car_mat <- 
  car_diffs %>%
  as.matrix()

car_mat[1:6, 1:6] %>%
  round(digits = 2)

car_diffs %>%
  hclust() %>%
  as.phylo() %>%
  plot(cex = .9, label.offset = 1)
```




### Exercise 9.4

```{r}
BigCities <-
  WorldCities %>%
  arrange(desc(population)) %>%
  head(4000) %>%
  select(longitude, latitude) 

glimpse(BigCities)
```

```{r}
set.seed(15)

city_clusts <-
  BigCities %>%
  kmeans(centers = 4) %>%
  fitted("classes") %>%
  as.character()

BigCities <- 
  BigCities %>%
  mutate(cluster = city_clusts)

BigCities %>%
  ggplot(aes(x = longitude, y = latitude)) +
  geom_point(aes(color = cluster), alpha = .5)

```
The algorithm divideds the points into k number of groups. For k = 2 to k = 6 the divisions seem to rather obvious. As k increases the divisions seem to make less sense since that many groups are not needed to accurately seperate the data.



### Exercise 9.5

```{r}
hof <-
  Batting %>%
  group_by(playerID) %>%
  inner_join(HallOfFame, by = c("playerID" = "playerID")) %>%
  filter(inducted == "Y" & votedBy == "BBWAA") %>%
  summarize(tH = sum(H), tHR = sum(HR), tRBI = sum(RBI), tSB = sum(SB)) %>%
  filter(tH > 1000)

glimpse(hof)
```

```{r}
hof_clusts <- 
  hof %>%
  select("tH", "tHR", "tRBI", "tSB") %>%
  kmeans(centers = 5)

hof_clusts

```






















